"""make_lease_start_end_nullable

Revision ID: cacb73f7cef5
Revises: 015
Create Date: 2026-05-09 18:02:02.562644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cacb73f7cef5'
down_revision: Union[str, None] = '015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('renters', 'lease_start',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('renters', 'lease_end',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('renters', 'lease_end',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('renters', 'lease_start',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
